# Generated by Django 6.0.1 on 2026-01-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
