# Generated by Django 6.0.1 on 2026-01-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cv_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cleaned_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
